places=[]
a=input("enter your favourite places")
b=input("enter your favourite places")
c=input("enter your favourite places")
d=input("enter your favourite places")
e=input("enter your favourite places")
places.insert(0,a)
places.insert(1,b)
places.insert(2,c)
places.insert(3,d)
places.insert(4,e)
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)